import { expect, test } from '@playwright/test'

test('multiple panes retain drafts through focus and workspace changes', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('region', { name: /실행 창$/ })).toHaveCount(3)
  await page.screenshot({ path: 'artifacts/mightyclaude-preview.png', fullPage: true })
  await page.getByRole('button', { name: '새 Claude', exact: true }).click()
  const draft = page.getByRole('textbox', { name: 'Claude 3 메시지 입력' })
  await draft.fill('이 초안은 다른 실행 창을 살펴봐도 유지되어야 합니다.')
  await page.getByRole('button', { name: '프로젝트 설계 창 확대' }).click()
  await expect(page.getByRole('region', { name: /실행 창$/ })).toHaveCount(1)
  await page.getByRole('button', { name: '그리드 보기' }).click()
  await expect(draft).toHaveValue('이 초안은 다른 실행 창을 살펴봐도 유지되어야 합니다.')
  await page.getByRole('button', { name: /폴더 열기/ }).click()
  await page.getByLabel('프로젝트 폴더 경로').fill('~/Projects/second-project')
  await page.getByRole('button', { name: '워크스페이스 추가', exact: true }).click()
  await expect(page.getByRole('region', { name: /실행 창$/ })).toHaveCount(1)
  await page.getByRole('button', { name: 'MightyClaude', exact: true }).click()
  await expect(page.getByRole('region', { name: /실행 창$/ })).toHaveCount(4)
  await expect(draft).toHaveValue('이 초안은 다른 실행 창을 살펴봐도 유지되어야 합니다.')
  await page.getByRole('button', { name: 'Claude 3 창 닫기' }).click()
  await expect(page.getByRole('region', { name: /실행 창$/ })).toHaveCount(3)
  expect(errors).toEqual([])
})

test('preview output is honest and layout, theme and output survive reload', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '프로젝트 설계 메시지 입력' }).fill('프로젝트 구조를 확인해 줘')
  await page.getByRole('button', { name: '프로젝트 설계 메시지 보내기' }).click()
  const output = page.getByRole('log', { name: '프로젝트 설계 출력' })
  await expect(output).toContainText('브라우저 미리보기에서는 명령을 실행하지 않습니다.')
  await page.getByRole('button', { name: '열 보기' }).click()
  await page.getByRole('button', { name: '밝은 테마로 전환' }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: '열 보기' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: '어두운 테마로 전환' })).toBeVisible()
  await expect(output).toContainText('프로젝트 구조를 확인해 줘')
  await expect(output).toContainText('브라우저 미리보기에서는 명령을 실행하지 않습니다.')
})

test('workspace removal repairs focus and empty state can create a new workspace', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'MightyClaude 워크스페이스 제거' }).click()
  await page.getByRole('button', { name: '워크스페이스 제거', exact: true }).click()
  await expect(page.getByRole('region', { name: /실행 창$/ })).toHaveCount(0)
  await page.getByRole('button', { name: '프로젝트 폴더 열기', exact: true }).click()
  await page.getByLabel('프로젝트 폴더 경로').fill('C:\\Projects\\new-app')
  await page.getByRole('button', { name: '워크스페이스 추가', exact: true }).click()
  await expect(page.getByRole('button', { name: 'new-app', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Claude 1 실행 창' })).toBeVisible()
  await page.getByRole('button', { name: '설정', exact: true }).click()
  await expect(page.getByText('2.1.271', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.setViewportSize({ width: 1024, height: 720 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
